"""Materialize Agent runtime configuration without editing user config files."""

from __future__ import annotations

import os
import re
import shlex
from pathlib import Path
from typing import Any


_ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_REPO_ROOT = Path(__file__).resolve().parents[2]


def benchmark_subprocess_env(job_env: dict[str, str]) -> dict[str, str]:
    """Build the environment for the `blockchain_node_benchmark.sh` subprocess.

    The benchmark pipeline's own analysis/report scripts call bare `python3`
    (not the Agent's `.venv-adk`, which is unrelated to the benchmark
    framework's own dependencies). `scripts/install_deps.sh` documents `.venv`
    (a separate, repo-root virtualenv) as the framework's own Python
    environment (`source .venv/bin/activate`) -- but the Agent process is not
    necessarily launched with that venv active, so its own `os.environ`
    (inherited by the subprocess) may resolve `python3` to the system
    interpreter, which lacks pandas/matplotlib/scipy/etc. That subprocess
    then fails partway through (at the analysis/report stage, well after
    Vegeta has already run) with confusing per-script failure messages rather
    than a clear "missing Python package" error. Prepending `.venv/bin` to
    PATH when it exists makes real benchmark execution work regardless of
    which venv (or none) launched the Agent itself, matching the framework's
    own documented setup rather than silently depending on it.
    """

    env = {**os.environ, **job_env}
    venv_bin = _REPO_ROOT / ".venv" / "bin"
    if venv_bin.is_dir():
        env["PATH"] = f"{venv_bin}{os.pathsep}{env.get('PATH', '')}"
    return env


def build_runtime_env(plan: dict[str, Any]) -> dict[str, str]:
    """Return the environment that should be used for one Agent job."""
    env: dict[str, str] = {}
    for source in (
        plan.get("execution", {}).get("environment", {}),
        plan.get("materialized_config", {}),
    ):
        if not isinstance(source, dict):
            continue
        for key, value in source.items():
            if not _ENV_NAME_RE.match(str(key)):
                continue
            if value is None:
                continue
            env[str(key)] = str(value)
    return env


def materialize_runtime_env(plan: dict[str, Any], run_dir: str | Path) -> str:
    """Write a sourceable runtime env file and return its path."""
    run_dir = Path(run_dir)
    run_dir.mkdir(parents=True, exist_ok=True)
    path = run_dir / "runtime.env"
    env = build_runtime_env(plan)
    override_path = _materialize_chain_config_override(plan, run_dir)
    if override_path:
        env["CHAIN_CONFIG_OVERRIDE_FILE"] = str(override_path)
    lines = [
        "# Generated by benchmark Agent for this job only.",
        "# Do not edit config/user_config.sh for Agent-generated runtime values.",
    ]
    for key in sorted(env):
        lines.append(f"export {key}={_shell_quote(env[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def load_runtime_env_file(path: str | Path) -> dict[str, str]:
    """Load a runtime env file generated by materialize_runtime_env."""
    env: dict[str, str] = {}
    for raw_line in Path(path).read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :]
        if "=" not in line:
            continue
        key, raw_value = line.split("=", 1)
        key = key.strip()
        if not _ENV_NAME_RE.match(key):
            continue
        try:
            values = shlex.split(raw_value, posix=True)
        except ValueError:
            values = [raw_value]
        env[key] = values[0] if values else ""
    return env


def _shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def _materialize_chain_config_override(plan: dict[str, Any], run_dir: Path) -> Path | None:
    override = plan.get("chain_config_override")
    if not isinstance(override, dict) or not override:
        return None
    path = run_dir / "chain_template.override.json"
    import json

    path.write_text(json.dumps(override, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path
