"""Shared semantic policy fragments used by every intent authority."""

FRAMED_REQUEST_SEMANTIC_POLICY = (
    "Interrogative, permission-seeking, hedging, and politeness wording that "
    "only frames whether the same present request can proceed belongs to that "
    "request. It is support, not an independent consultation, omitted demand, "
    "or unresolved unit. It becomes an independent consultation only when the "
    "source separately asks for information, explanation, comparison, "
    "validation, consequences, or another result beyond whether that same "
    "request can proceed. "
)

PENDING_CANDIDATE_SEMANTIC_POLICY = (
    "A present commitment is a pending answer only when it authorizes one action "
    "or option accepted by the exact signed pending contract, or supplies one "
    "admissible manual value for that contract. Refusal, deferral, cancellation, "
    "or navigation away from a pending question is a pending answer only when the "
    "signed contract declares that exact effect as an accepted option or action. "
    "Committing to withhold an answer is not authorization of the pending action. "
    "Otherwise preserve that source as support for its independently grounded "
    "operation or as unresolved work. "
    "Syntax candidates are not selections. A value mentioned only as an example, "
    "quotation, rejected option, negated operation, correction target, or value "
    "the user explicitly says not to apply does not answer the pending question. "
    "Preserve any independent explanation or correction demand instead. "
    "A source may affirm one exact candidate while excluding a category of "
    "alternatives. Excluding documentation, sample, old, or unrelated alternatives "
    "does not negate the separately affirmed candidate. Preserve unambiguous "
    "operation framing and alternative exclusions as support for that candidate; "
    "a negation or example of the selected candidate remains non-selecting. "
    "When the source rejects one or more declared options and affirmatively requests "
    "the meaning or action of another declared option, select only the affirmed "
    "option. The rejection is contrastive evidence for that selection, never an "
    "answer selecting a rejected option. When the affirmed declared option itself "
    "performs the requested navigation or mutation, represent the complete contrast "
    "as one pending selection rather than duplicating that option action as an "
    "independent sibling demand. "
    "When two or more values satisfy the active manual pending contract, never "
    "select one from list order. Exactly one candidate must be distinguished as "
    "selected and every other candidate must be distinguished as rejected, old, "
    "example-only, or otherwise not selected. A conjunction, disjunction, "
    "slash-separated list, comparison, or bare sequence is unresolved. "
)
