"""Small language policy helpers for terminal UX."""

from __future__ import annotations

import re


_CJK_RE = re.compile(r"[\u3400-\u9fff]")


def detect_language(text: str, default: str = "en") -> str:
    """Return the preferred response language for a user turn."""
    if _CJK_RE.search(text or ""):
        return "zh"
    if default in {"zh", "en"}:
        return default
    return "en"


def t(language: str, key: str, **values: object) -> str:
    """Translate a small fixed terminal message."""
    table = _ZH if language == "zh" else _EN
    template = table.get(key) or _EN.get(key) or key
    return template.format(**values)


_ZH = {
    "welcome": "AnyChain Benchmark Agent 已启动。",
    "mode": "当前模型配置：provider={provider}, model={model}, auth={auth_mode}",
    "adk": "ADK runtime：{status}",
    "job_found": "检测到最近 job：{job_id}，状态：{status}",
    "job_next_actions": "可选下一步：{actions}",
    "job_none": "没有检测到历史 job。",
    "prompt": "User> ",
    "agent": "Agent> {message}",
    "bye": "已退出 AnyChain Benchmark Agent。",
    "help": "你可以说：测试 solana、使用 fake-node、doctor、jobs、status、help、exit。",
    "startup_doctor_start": "正在启动时执行只读环境和依赖检查。",
    "startup_doctor_summary": "启动检查完成：status={status}，cloud={cloud}，deployment={deployment}，缺失依赖={missing}，能力={chains} chains / {methods} RPC methods。",
    "doctor_start": "正在执行只读环境检查。",
    "doctor_summary": "检查完成：status={status}，缺失依赖={missing}，能力={chains} chains / {methods} RPC methods。",
    "dependency_offer": "检测到缺失依赖：{missing}。我可以在你确认后运行 scripts/install_deps.sh --yes。是否允许？[Y/n]",
    "dependency_declined": "已跳过依赖安装。后续真实 benchmark 可能仍会被 preflight 阻止。",
    "dependency_install_start": "开始安装 benchmark 依赖。这一步可能需要一些时间。",
    "dependency_install_done": "依赖安装命令完成，exit_code={exit_code}。",
    "agent_runtime_offer": "检测到 Agent runtime 依赖缺失：google-adk。是否允许我运行 scripts/install_agent_deps.sh --yes 安装到隔离环境？[Y/n]",
    "agent_runtime_declined": "已跳过 Agent runtime 安装。底层 LLM/ADK 能力仍不可用。",
    "agent_runtime_install_start": "开始安装 Agent runtime 依赖到隔离环境。",
    "agent_runtime_install_done": "Agent runtime 安装命令完成，exit_code={exit_code}。",
    "llm_config_warning": "LLM 配置还不完整：{errors}",
    "jobs_empty": "没有找到 job。",
    "jobs_header": "最近 job：",
    "state_reset": "已重置当前 Agent workflow。你可以重新描述要测试的链、节点和目标。",
    "unknown": "我已经记录你的输入。下一步会由 benchmark workflow 判断需要确认的配置；当前可先输入 doctor 或“测试 solana”。",
    "framework_context_loaded": "已加载框架事实：{chains} chains，{families} adapter families，{methods} RPC methods，fake-node fixtures={fixtures}。",
    "ask_chain": "你要压测哪个区块链节点？当前可选链示例：{chains}。请直接输入链名，例如 solana。",
    "ask_chain_for_target": "已记录目标类型为 {target}，但还不知道要测试哪个链。当前可选链示例：{chains}。请直接输入链名，例如 solana。",
    "invalid_chain": "这个链名不在当前 config/chains 中。请重新输入链名；示例：{chains}。",
    "benchmark_chain": "我理解你要测试 {chain}。是否确认这个链？[Y/n]",
    "select_target": "请选择测试目标：[1] fake-node 闭环测试 / [2] real-node 真实节点。你也可以直接输入 fake-node 或 real-node。",
    "invalid_target_type": "无法识别测试目标。请输入 1/fake-node，或 2/real-node。",
    "fake_node_selected": "已选择 fake-node。这个模式不需要真实 LOCAL_RPC_URL，但仍需要确认 RPC mode、method、weight 和必要的 TARGET_* 样本。",
    "ask_rpc_mode": "请选择 RPC 模式：[1] single 单方法 / [2] mixed 多方法加权。",
    "confirm_single_method": "默认先使用 single workload。下一步需要确认具体 RPC method 和必要的 TARGET_* 样本。",
    "confirm_mixed_weights": "mixed workload 需要确认每个 RPC method 的权重，且总和必须等于 100。",
    "ask_detected_single_method": "链模板中 single RPC method 是 {method}。是否使用这个方法？[Y/n] 如果不使用，请输入 n 后提供自定义 method。",
    "ask_detected_mixed_weights": "链模板中 mixed 权重是 {weights}。是否使用这组权重？[Y/n] 如果不使用，请输入 n 后提供自定义权重。",
    "ask_custom_single_method": "请提供 single 模式要测试的 RPC method，例如 getSlot。",
    "ask_custom_mixed_weights": "请提供 mixed 权重，格式例如 getSlot=70,getBlockHeight=30，总和必须为 100。",
    "confirm_param_samples": "还需要确认所选 RPC method 的 TARGET_* 参数样本。使用链模板默认样本继续吗？[Y/n]",
    "gate_blocked": "现在还不能执行 smoke，仍缺少：{missing}",
    "gate_ready": "配置门禁已通过，可以进入 smoke 前确认。",
    "prepare_smoke_offer": "我将根据已确认配置生成 benchmark plan、执行 preflight，并写入本次 job 的 runtime.env 预览。是否继续？[Y/n]",
    "prepare_start": "正在生成 plan 并执行 preflight。",
    "prepare_warnings": "preflight 警告：{warnings}",
    "prepare_ok": "preflight 通过。plan={plan_file}，runbook={runbook_file}。是否执行 mock smoke 生命周期验证？[Y/n]",
    "prepare_blocked": "preflight 被阻止：{blockers}。plan={plan_file}",
    "mock_smoke_start": "正在执行 mock smoke 生命周期验证，不会向节点产生真实流量。",
    "mock_smoke_done": "mock smoke 完成：job={job_id}，status={status}，runtime_env={runtime_env_file}，artifact_index={artifact_index}",
    "smoke_declined": "已暂停 smoke。你可以继续调整配置，或输入 status/jobs 查看状态。",
    "real_node_selected": "已选择真实节点。后续需要确认 LOCAL_RPC_URL、进程名、磁盘、网络和 workload。",
    "ask_required_value": "请提供或确认 {name}。",
    "ask_detected_value_confirm": "检测到 {name}={value}。是否使用这个值？[Y/n] 如果不正确，请直接输入新值。",
    "recorded_value": "已记录 {name}。",
    "real_node_required_done": "真实节点必填运行变量已记录完毕。",
    "benchmark_required_done": "benchmark 基础运行变量已记录完毕。",
    "ask_mainnet_rpc_url": "请提供 MAINNET_RPC_URL；如果该链使用 chain template 默认主网/同步健康策略，请输入 default 或 skip。",
    "ask_network_interface_confirm": "检测到默认网卡 {value}。是否使用它作为 NETWORK_INTERFACE？[Y/n] 如果不正确，请直接输入网卡名。",
    "disk_candidates": "检测到以下磁盘候选：\n{candidates}",
    "ask_ledger_device_choice": "请选择 LEDGER_DEVICE：输入编号，或直接输入设备名，例如 nvme1n1、sdb。",
    "ask_accounts_device_presence": "这个节点是否有单独的 ACCOUNTS/状态数据磁盘？[Y/n]",
    "ask_accounts_device_choice": "请选择 ACCOUNTS_DEVICE：输入编号，或直接输入设备名。",
    "accounts_device_skipped": "已确认没有单独的 ACCOUNTS_DEVICE。",
    "ask_advanced_config_review": "基础环境变量已确认。高级阈值默认使用 config/internal_config.sh。是否需要查看高级配置摘要？[y/N]",
    "advanced_config_summary": "高级配置默认保留：瓶颈阈值、成功率阈值、延迟阈值、区块同步健康阈值均来自 config/internal_config.sh。你之后可以通过高级配置单独调整。",
    "advanced_config_skipped": "已使用默认高级配置，后续会进入 RPC workload 配置。",
    "invalid_choice": "这个选择无法识别。请重新输入编号，或直接输入设备名。",
    "invalid_empty": "这个值不能为空，请重新提供。",
    "invalid_url": "{name} 不是有效的 http/https/ws/wss endpoint，请重新提供。",
    "invalid_numeric": "{name} 必须是大于 0 的数字，请重新提供。",
    "invalid_mixed_weights": "mixed 权重格式无法解析。请使用类似 getSlot=70,getBlockHeight=30 的格式。",
    "invalid_mixed_weight_total": "mixed 权重总和必须等于 100；当前总和是 {total}，请重新提供。",
    "not_manual_export": "这个问题应该由 Agent 写入 runtime env 或子进程 env 处理，不应该要求你手动 export PATH。",
    "interrupted": "已中断当前输入。输入 exit 退出，或继续告诉我你的测试目标。",
    "ctrl_c_exit": "收到 Ctrl+C，正在退出 AnyChain Benchmark Agent。",
    "adk_missing_hint": "注意：google-adk 当前不可用。请先运行 bash scripts/install_agent_deps.sh --yes；在此之前，Agent 只能使用有限的终端 workflow 和可用的直连 LLM provider。",
}


_EN = {
    "welcome": "AnyChain Benchmark Agent started.",
    "mode": "Model config: provider={provider}, model={model}, auth={auth_mode}",
    "adk": "ADK runtime: {status}",
    "job_found": "Found latest job: {job_id}, status: {status}",
    "job_next_actions": "Available next actions: {actions}",
    "job_none": "No previous job was found.",
    "prompt": "User> ",
    "agent": "Agent> {message}",
    "bye": "Exited AnyChain Benchmark Agent.",
    "help": "Try: benchmark solana, use fake-node, doctor, jobs, status, help, exit.",
    "startup_doctor_start": "Running startup read-only environment and dependency diagnostics.",
    "startup_doctor_summary": "Startup diagnostics complete: status={status}, cloud={cloud}, deployment={deployment}, missing dependencies={missing}, capabilities={chains} chains / {methods} RPC methods.",
    "doctor_start": "Running read-only environment diagnostics.",
    "doctor_summary": "Doctor complete: status={status}, missing dependencies={missing}, capabilities={chains} chains / {methods} RPC methods.",
    "dependency_offer": "Missing dependencies detected: {missing}. I can run scripts/install_deps.sh --yes after your confirmation. Allow this? [Y/n]",
    "dependency_declined": "Skipped dependency installation. A real benchmark may still be blocked by preflight.",
    "dependency_install_start": "Starting benchmark dependency installation. This may take a while.",
    "dependency_install_done": "Dependency installation command completed, exit_code={exit_code}.",
    "agent_runtime_offer": "Agent runtime dependency is missing: google-adk. Allow me to run scripts/install_agent_deps.sh --yes and install it into an isolated environment? [Y/n]",
    "agent_runtime_declined": "Skipped Agent runtime installation. Underlying LLM/ADK capabilities remain unavailable.",
    "agent_runtime_install_start": "Starting Agent runtime dependency installation into the isolated environment.",
    "agent_runtime_install_done": "Agent runtime installation command completed, exit_code={exit_code}.",
    "llm_config_warning": "LLM configuration is incomplete: {errors}",
    "jobs_empty": "No jobs found.",
    "jobs_header": "Recent jobs:",
    "state_reset": "Reset the current Agent workflow. You can describe the chain, node, and benchmark goal again.",
    "unknown": "I recorded your input. The benchmark workflow will decide the next required configuration; you can start with doctor or benchmark solana.",
    "framework_context_loaded": "Loaded framework facts: {chains} chains, {families} adapter families, {methods} RPC methods, fake-node fixtures={fixtures}.",
    "ask_chain": "Which blockchain node do you want to benchmark? Supported chain examples: {chains}. Type a chain name, for example solana.",
    "ask_chain_for_target": "Recorded target type as {target}, but the chain is still unknown. Supported chain examples: {chains}. Type a chain name, for example solana.",
    "invalid_chain": "That chain is not in the current config/chains inventory. Type a valid chain name; examples: {chains}.",
    "benchmark_chain": "I understand you want to benchmark {chain}. Confirm this chain? [Y/n]",
    "select_target": "Choose the benchmark target: [1] fake-node closed-loop test / [2] real-node. You can also type fake-node or real-node.",
    "invalid_target_type": "I could not recognize the target. Type 1/fake-node or 2/real-node.",
    "fake_node_selected": "Selected fake-node. This mode does not need a real LOCAL_RPC_URL, but still needs RPC mode, method, weight, and required TARGET_* samples.",
    "ask_rpc_mode": "Choose RPC mode: [1] single method / [2] weighted mixed methods.",
    "confirm_single_method": "Defaulting to a single workload. Next we need to confirm the RPC method and required TARGET_* samples.",
    "confirm_mixed_weights": "A mixed workload requires per-method weights, and the total must equal 100.",
    "ask_detected_single_method": "The chain template single RPC method is {method}. Use this method? [Y/n] If not, type n and then provide a custom method.",
    "ask_detected_mixed_weights": "The chain template mixed weights are {weights}. Use these weights? [Y/n] If not, type n and then provide custom weights.",
    "ask_custom_single_method": "Provide the RPC method for single mode, for example getSlot.",
    "ask_custom_mixed_weights": "Provide mixed weights, for example getSlot=70,getBlockHeight=30. The total must be 100.",
    "confirm_param_samples": "We still need to confirm TARGET_* parameter samples for the selected RPC method. Continue with chain-template defaults? [Y/n]",
    "gate_blocked": "Smoke cannot run yet. Missing: {missing}",
    "gate_ready": "Configuration gates passed; ready for smoke confirmation.",
    "prepare_smoke_offer": "I will generate a benchmark plan, run preflight, and write the job-local runtime.env preview from the confirmed configuration. Continue? [Y/n]",
    "prepare_start": "Generating plan and running preflight.",
    "prepare_warnings": "Preflight warnings: {warnings}",
    "prepare_ok": "Preflight passed. plan={plan_file}, runbook={runbook_file}. Run a mock smoke lifecycle verification now? [Y/n]",
    "prepare_blocked": "Preflight is blocked: {blockers}. plan={plan_file}",
    "mock_smoke_start": "Running mock smoke lifecycle verification. This does not send real node traffic.",
    "mock_smoke_done": "Mock smoke completed: job={job_id}, status={status}, runtime_env={runtime_env_file}, artifact_index={artifact_index}",
    "smoke_declined": "Smoke is paused. You can continue adjusting configuration, or type status/jobs.",
    "real_node_selected": "Selected real node. Next we need LOCAL_RPC_URL, process names, disks, network, and workload.",
    "ask_required_value": "Please provide or confirm {name}.",
    "ask_detected_value_confirm": "Detected {name}={value}. Use this value? [Y/n] If not, type the correct value.",
    "recorded_value": "Recorded {name}.",
    "real_node_required_done": "Required real-node runtime variables have been recorded.",
    "benchmark_required_done": "Benchmark runtime baseline variables have been recorded.",
    "ask_mainnet_rpc_url": "Provide MAINNET_RPC_URL; if this chain should use chain-template defaults for mainnet/sync-health, type default or skip.",
    "ask_network_interface_confirm": "Detected default network interface {value}. Use it as NETWORK_INTERFACE? [Y/n] If not, type the interface name.",
    "disk_candidates": "Detected disk candidates:\n{candidates}",
    "ask_ledger_device_choice": "Choose LEDGER_DEVICE: enter a number, or type a device name such as nvme1n1 or sdb.",
    "ask_accounts_device_presence": "Does this node have a separate ACCOUNTS/state-data disk? [Y/n]",
    "ask_accounts_device_choice": "Choose ACCOUNTS_DEVICE: enter a number, or type a device name.",
    "accounts_device_skipped": "Confirmed: no separate ACCOUNTS_DEVICE.",
    "ask_advanced_config_review": "Baseline environment values are confirmed. Advanced thresholds will use config/internal_config.sh by default. Review advanced configuration summary? [y/N]",
    "advanced_config_summary": "Keeping advanced defaults: bottleneck thresholds, success-rate threshold, latency threshold, and sync-health thresholds come from config/internal_config.sh. You can tune them later through advanced configuration.",
    "advanced_config_skipped": "Using default advanced configuration; continuing to RPC workload setup.",
    "invalid_choice": "I could not recognize that choice. Enter a number, or type the device name directly.",
    "invalid_empty": "This value cannot be empty. Please provide it again.",
    "invalid_url": "{name} is not a valid http/https/ws/wss endpoint. Please provide it again.",
    "invalid_numeric": "{name} must be a number greater than 0. Please provide it again.",
    "invalid_mixed_weights": "Could not parse mixed weights. Use a format like getSlot=70,getBlockHeight=30.",
    "invalid_mixed_weight_total": "Mixed weights must total 100; current total is {total}. Please provide them again.",
    "not_manual_export": "The Agent should fix this through runtime env or child-process env, not ask you to manually export PATH.",
    "interrupted": "Interrupted the current input. Type exit to quit, or continue with your benchmark goal.",
    "ctrl_c_exit": "Received Ctrl+C; exiting AnyChain Benchmark Agent.",
    "adk_missing_hint": "Note: google-adk is not available. Run bash scripts/install_agent_deps.sh --yes first; until then, the Agent can only use limited terminal workflow and any available direct LLM provider.",
}
